# Generated by Django 4.2.2 on 2023-07-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_creates_at_room_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='generate_unique_code', max_length=8, unique=True),
        ),
    ]
