# Generated by Django 4.2.2 on 2023-07-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_room_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='generate_unique_code', max_length=8, unique=True),
        ),
    ]
