# Generated by Django 4.2.7 on 2023-11-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_room_code_alter_room_votes_to_skip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default='generate_unique_code', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='votes_to_skip',
            field=models.IntegerField(default='0', unique=True),
        ),
    ]
